<a href="https://colab.research.google.com/github/Nungdoo/deep-learning-study/blob/main/exercise08_1%2C2%2C3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 08-1

합성곱 구현하기

In [2]:
import numpy as np

w = np.array([2, 1, 5, 3])
x = np.array([2, 8, 3, 7, 1, 2, 0, 4, 5])

w_r = np.flip(w)
print('w_r :', w_r)

for i in range(6):
  print(np.dot(x[i:i+4], w_r))

from scipy.signal import convolve
convolve(x, w, mode='valid')



w_r : [3 5 1 2]
63
48
49
28
21
20


array([63, 48, 49, 28, 21, 20])

교차 상관 연산 구현하기

In [4]:
from scipy.signal import correlate

# 밸리드 패딩
print(correlate(x, w, mode='valid'))

# 풀 패딩
print(correlate(x, w, mode='full'))

# 세임 패딩
print(correlate(x, w, mode='same'))

[48 57 24 25 16 39]
[ 6 34 51 48 57 24 25 16 39 29 13 10]
[34 51 48 57 24 25 16 39 29]


2차원 배열의 합성곱

In [6]:
x = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
w = np.array([[2, 0], [0, 0]])

from scipy.signal import correlate2d

# 밸리드 패딩
print(correlate2d(x, w, mode='valid'))

# 세임 패딩
print(correlate2d(x, w, mode='same'))

[[ 2  4]
 [ 8 10]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


텐서플로로 합성곱 수행
- reshape() 2차원 > 4차원 변경
- astype() 실수형 데이터로 변경
- conv2d()는 다차원 배열인 Tensor 객체를 반환함
- Tensor 객체의 numpy() 함수를 이용해 넘파이 배열로 변환

In [12]:
import tensorflow as tf
import numpy as np

x_4d = x.astype(np.float).reshape(1, 3, 3, 1)
w_4d = w.reshape(2, 2, 1, 1)

c_out = tf.nn.conv2d(x_4d, w_4d, strides=1, padding='SAME')
c_out.numpy().reshape(3, 3)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  after removing the cwd from sys.path.


array([[ 2.,  4.,  6.],
       [ 8., 10., 12.],
       [14., 16., 18.]])

# 08-2

최대 풀링

In [13]:
x = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])
x = x.reshape(1, 4, 4, 1)

p_out = tf.nn.max_pool2d(x, ksize=2, strides=2, padding='VALID')
p_out.numpy().reshape(2, 2)

array([[ 6.,  8.],
       [14., 16.]], dtype=float32)

# 08-3

렐루 함수 구현하기

In [17]:
def relu_test(x):
  return np.maximum(x, 0)

x = np.array([-1, 2, -3, 4, -5])
print(relu_test(x))

r_out = tf.nn.relu(x)
print(r_out.numpy())

[0 2 0 4 0]
[0 2 0 4 0]
